git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_C1_S1_L001_BCHLT_bowtie.bam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_C1_S1_L001_BCHLT_bowtie.bed' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_C1_S1_L001_BCHLT_bowtie.bedgraph' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_C1_S1_L001_BCHLT_bowtie.sam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_C1_S1_L001_BCHLT_bowtie_N1.sam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_C1_S1_L001_BCHLT_bowtie_sorted.bam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_C1_S1_L001_BCHLT_bowtie_sorted.bed' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie.bam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie.bed' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie.bedgraph' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie.sam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie_N1.sam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie_sorted.bam' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie_sorted.bed' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/B_SC-BLESS_NB_S2_L001_BCHLT_bowtie.sam' --prune-empty --tag-name-filter cat -- --all

git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.2.bt2' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.3.bt2' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.1.bt2' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.4.bt2' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.rev.1.bt2' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch hg_mapping/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.rev.2.bt2' --prune-empty --tag-name-filter cat -- --all
